# Generated by Django 6.1.2 on 2026-10-07 08:33

import meetalign.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetalign', '0012_team_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='invite_code',
            field=models.CharField(default=meetalign.models._generate_invite_code, editable=False, max_length=8, unique=True),
        ),
    ]
