# Generated by Django 6.1.2 on 2026-10-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetalign', '0013_team_invite_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='error_message',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
